CC=/opt/cuda-4.2/cuda/bin/nvcc
LIBS= -lglut -lGL -lGLU
INCLUDES=-I./ -I/usr/include -I/usr/local/cuda/include/ 
CCFLAGS= 
OBJECTS= MBSet.o

# --- targets
all:  MBSet
MBSet:	$(OBJECTS)
	$(CC) -o MBSet $(CCFLAGS) $(INCLUDES) $(OBJECTS) $(LIBS) 

MBSet.o: MBSet.cu
	$(CC) $(CCFLAGS) $(INCLUDES) -c MBSet.cu


clean:
	rm -f MBSet $(OBJECTS)
